### ISSUE TITLE
Looks bad with dark Alfred theme

### ISSUE THREAD

**Issue by valpackett** [wookayin/alfred-latex-symbols-workflow#1]
Hi! Thank you for your workflow, I really needed that :)

I think you need to add white background to the symbols to avoid this:

![screen shot 2015-04-30 at 8 28 28 pm](https://cloud.githubusercontent.com/assets/208340/7418561/7bff00be-ef77-11e4-9613-7ce918316063.png)

Also, why only prefix matching? I want to find `\Rightarrow` by searching `arrow`...

**Comment by wookayin** [comment]
Hi @myfreeweb, thanks for the report. For dark themes, it would be better (i) to have inverted colors (i.e. white forecolor with transparent background) or (ii) to add white bakground as suggested by you.

However, as I was using bright themes when first trying to write this workflow, I had thought white background looks a little bit clumsy on bright backgrounds. So I think I have to might detect the background color.

Fortunately, from Alfred 2.4, there is an [environment variable](http://support.alfredapp.com/kb:script-environment-variables) `alfred_theme_background` so it seems that we can detect the background color!

I hope I can add this feature very soon.

**Comment by valpackett** [comment]
Well, you can have a white background with rounded corners :D

**Comment by wookayin** [comment]
Hi @unrelentingtech, do you still need this?

**Comment by valpackett** [comment]
haha no, I haven't even used macOS in years

**Comment by xiajunwen1007** [comment]
> Hi @unrelentingtech, do you still need this?

I need this so much,, do you have any plan of supporting it?

**Comment by wookayin** [comment]
I added white icons in #6. Please try out [v1.1.0](https://www.npmjs.com/package/alfred-latex-symbols/v/1.1.0) and thank you for waiting for this feature for a long time!
